# Generated by Django 3.1.4 on 2020-12-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20201223_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
